#pragma once

// Name: Medieval Dynasty, Version: 0.6.0.3


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function UI_CheatMenu.UI_CheatMenu_C.FillWithAnimals
struct UUI_CheatMenu_C_FillWithAnimals_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.PreConstruct
struct UUI_CheatMenu_C_PreConstruct_Params
{
	bool                                               IsDesignTime;                                              // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_AddItem_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_AddItem_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_DemoItems_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_DemoItems_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_FieldItems_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_FieldItems_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__Button_408_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__Button_408_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.Construct
struct UUI_CheatMenu_C_Construct_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Technology_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Technology_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Technology_1_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Technology_1_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_BuildPermission_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_BuildPermission_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_BuildingItems_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_BuildingItems_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Technology_50_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Technology_50_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_FinishAllBuildings_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_FinishAllBuildings_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_AddItem_1_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_AddItem_1_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_AddAnimal_1_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_AddAnimal_1_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_SpawnNPC_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_SpawnNPC_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_SkipSeason_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_SkipSeason_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_InfiniteWeight_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_InfiniteWeight_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_IncreaseSkillPoints_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_IncreaseSkillPoints_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_InfiniteStamina_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_InfiniteStamina_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_GodMode_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_GodMode_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_ArmorItems_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_ArmorItems_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_ChangeWeather_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_ChangeWeather_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_FreeCamera_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_FreeCamera_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__Button_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__Button_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Quicksave_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Quicksave_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_OwnershipVisibility_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_OwnershipVisibility_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_SchemeUnlock_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_SchemeUnlock_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_FillWithAnimals_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_FillWithAnimals_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_IncreaseAge_K2Node_ComponentBoundEvent_29_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_IncreaseAge_K2Node_ComponentBoundEvent_29_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_GetStory_K2Node_ComponentBoundEvent_32_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_GetStory_K2Node_ComponentBoundEvent_32_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_IncreaseReputation_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_IncreaseReputation_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_ToggleAnimalsSpawners_K2Node_ComponentBoundEvent_31_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_ToggleAnimalsSpawners_K2Node_ComponentBoundEvent_31_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_TeleportToLocation_K2Node_ComponentBoundEvent_33_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_TeleportToLocation_K2Node_ComponentBoundEvent_33_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_FillWithFamilies_K2Node_ComponentBoundEvent_35_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_FillWithFamilies_K2Node_ComponentBoundEvent_35_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.OnTextChanged_Event_1
struct UUI_CheatMenu_C_OnTextChanged_Event_1_Params
{
	struct FText                                       Text;                                                      // (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Autosave_K2Node_ComponentBoundEvent_36_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Autosave_K2Node_ComponentBoundEvent_36_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_GetGenericQuest_K2Node_ComponentBoundEvent_37_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_GetGenericQuest_K2Node_ComponentBoundEvent_37_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_SpawnGhost_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_SpawnGhost_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.OnTextChanged_Event_2
struct UUI_CheatMenu_C_OnTextChanged_Event_2_Params
{
	struct FText                                       Text;                                                      // (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_RerollTaxQuest_K2Node_ComponentBoundEvent_39_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_RerollTaxQuest_K2Node_ComponentBoundEvent_39_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_GetEvent_K2Node_ComponentBoundEvent_40_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_GetEvent_K2Node_ComponentBoundEvent_40_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_GetChallenge_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_GetChallenge_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_KingdomCheat_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_KingdomCheat_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_GetCheckQuest_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_GetCheckQuest_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Die_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Die_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_FillWithAnimals_1_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_FillWithAnimals_1_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Time-_K2Node_ComponentBoundEvent_34_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Time__K2Node_ComponentBoundEvent_34_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__btn_Time+_K2Node_ComponentBoundEvent_43_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__btn_Time__K2Node_ComponentBoundEvent_43_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_StopTimeFlow_K2Node_ComponentBoundEvent_44_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_StopTimeFlow_K2Node_ComponentBoundEvent_44_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_RerollPOIs_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_RerollPOIs_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_NewGeneratorQuest_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_NewGeneratorQuest_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_GetStory_Replace_K2Node_ComponentBoundEvent_47_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_GetStory_Replace_K2Node_ComponentBoundEvent_47_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_ChromaEffect_K2Node_ComponentBoundEvent_48_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_ChromaEffect_K2Node_ComponentBoundEvent_48_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_PlayWedding_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_PlayWedding_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_ToggleAnimalsSpawners_1_K2Node_ComponentBoundEvent_50_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_ToggleAnimalsSpawners_1_K2Node_ComponentBoundEvent_50_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.BndEvt__UI_CheatMenu_btn_ToggleAnimalsSpawners_2_K2Node_ComponentBoundEvent_51_OnButtonClickedEvent__DelegateSignature
struct UUI_CheatMenu_C_BndEvt__UI_CheatMenu_btn_ToggleAnimalsSpawners_2_K2Node_ComponentBoundEvent_51_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function UI_CheatMenu.UI_CheatMenu_C.ExecuteUbergraph_UI_CheatMenu
struct UUI_CheatMenu_C_ExecuteUbergraph_UI_CheatMenu_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
